# Generated by Django 2.2.7 on 2019-11-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_emergency',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_msg',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_tel',
            field=models.TextField(max_length=15),
        ),
    ]
