# Generated by Django 2.2.7 on 2019-11-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='member_pw',
        ),
    ]
