# Generated by Django 2.2.7 on 2019-11-25 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191125_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='member_emergency',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='휴대전화 형식은 xxx-xxxx-xxxx입니다.', regex='^\\d{3}-\\d{3,4}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='member_tel',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='휴대전화 형식은 xxx-xxxx-xxxx입니다.', regex='^\\d{3}-\\d{3,4}-\\d{4}$')]),
        ),
    ]
