# Generated by Django 2.2.7 on 2019-11-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV_Kind',
            fields=[
                ('CCTV_KIND', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('CCTV_RADIUS', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Streetlamp_Kind',
            fields=[
                ('STR_KIND', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('STR_RADIUS', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Streetlamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR_LONGITUDE', models.CharField(max_length=20)),
                ('STR_LATITUDE', models.CharField(max_length=20)),
                ('STR_KIND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeLoad.Streetlamp_Kind')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCTV_LONGITUDE', models.CharField(max_length=20)),
                ('CCTV_LATITUDE', models.CharField(max_length=20)),
                ('CCTV_KIND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeLoad.CCTV_Kind')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
