# Generated by Django 2.2.7 on 2019-11-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCTV_RADIUS', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='StreetlampKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR_RADIUS', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Streetlamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR_ADDRESS_NAME', models.CharField(max_length=50)),
                ('STR_LONGITUDE', models.CharField(max_length=20)),
                ('STR_LATITUDE', models.CharField(max_length=20)),
                ('STR_KIND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeLoad.StreetlampKind')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCTV_ADDRESS_NAME', models.CharField(max_length=50)),
                ('CCTV_LONGITUDE', models.CharField(max_length=20)),
                ('CCTV_LATITUDE', models.CharField(max_length=20)),
                ('CCTV_KIND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeLoad.CCTVKind')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
