# Generated by Django 2.2.7 on 2019-11-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safeLoad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cctv',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='cctvkind',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='streetlamp',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='streetlampkind',
            options={'ordering': ['pk']},
        ),
    ]
