# Generated by Django 2.2.7 on 2019-11-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeLoad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctv_kind',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streetlamp_kind',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cctv_kind',
            name='CCTV_KIND',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='streetlamp_kind',
            name='STR_KIND',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
