# Generated by Django 2.2.6 on 2019-10-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
