# Generated by Django 2.2.6 on 2019-11-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='open_date',
            field=models.TextField(),
        ),
    ]
